### ISSUE TITLE
Actividad8_ReconocimientoGPS

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/actividad-8-reconocimeinto-gps-team-vo#1]

**Comment by KarlaV0** [comment]
[Actividad 8_ReconociminetoGPS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-reconocimeinto-gps-team-vo/files/15267380/Actividad.8_ReconociminetoGPS.pdf)

**Comment by MLR062998** [comment]
20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
